export const featuredCourses = [
     {
        id: "mastering-digital-marketing-with-generative-ai",
        title: "Mastering Digital Marketing with Generative AI",
        description: "Learn digital marketing using Generative AI for smarter content and champaigns",
        duration: "6",
        level: "Beginner to Advanced",
        price: "₹55,000",
        discountPrice: "₹35,000",
        // monthlyPrice: "₹5,333/month",
        rating: 4.9,
        students: "3,400+",
        image: "/masteringdigital.jpg?height=250&width=400&text=Digital+Marketing+AI",
        category: "Digital Marketing",
        instructor: "Sarah Johnson",
        skills: ["AI Tools", "Analytics", "Google Ads", "Facebook Marketing", "SEO"],
    },
    {
        id: "digital-marketing-with-ai",
        title: "Digital Marketing with AI",
        description: "Master digital marketing strategies powered by artificial intelligence and automation tools.",
        duration: "3",
        level: "Beginner to Advanced",
        price: "₹35,000",
        discountPrice: "₹25,000",
        monthlyPrice: "₹5,333/month",
        rating: 4.9,
        students: "3,200+",
        image: "/how-artificial-intelligence-is-changing-the-world-of-digital-marketing.webp?height=250&width=400&text=Digital+Marketing+AI",
        category: "Digital Marketing",
        instructor: "Sarah Johnson",
        skills: ["AI Tools", "Analytics", "Google Ads", "Facebook Marketing", "SEO"],
    },
    {
        id: "data-science",
        title: "Data Science with Python",
        description: "Comprehensive data science program covering Python, machine learning, and statistical analysis.",
        duration: "12",
        level: "Beginner to Advanced",
        price: "₹55,000",
        discountPrice: "₹35,000",
        monthlyPrice: "₹2,333/month",
        rating: 4.8,
        students: "5,500+",
        image: "/1_LxP1qwPjHE1CDFmLBh3bxQ.jpg?height=250&width=400&text=Data+Science+Python",
        category: "Data Science",
        instructor: "Dr. Rajesh Kumar",
        skills: ["Python", "Pandas", "NumPy", "Scikit-learn", "Tableau"],
    },
    {
        id: "ai-ml",
        title: "AI & ML Master Program",
        description: "Advanced program covering deep learning, neural networks, and AI implementation strategies.",
        duration: "10",
        level: "Intermediate",
        price: "₹55,000",
        discountPrice: "₹35,000",
        monthlyPrice: "₹2,850/month",
        rating: 4.7,
        students: "4,800+",
        image: "/header-graphic-datascience.webp?height=250&width=400&text=AI+Machine+Learning",
        category: "AI & ML",
        instructor: "Prof. Anita Sharma",
        skills: ["TensorFlow", "PyTorch", "Deep Learning", "NLP", "Computer Vision"],
    },
    {
        id: "aws",
        title: "AWS Cloud Computing",
        description: "Complete AWS certification program covering cloud architecture and deployment strategies.",
        duration: "8",
        level: "Beginner",
        price: "₹55,000",
        discountPrice: "₹35,000",
        monthlyPrice: "₹5,400/month",
        rating: 4.6,
        students: "6,200+",
        image: "/AWS-Services-main-banner.svg?height=250&width=400&text=AWS+Cloud+Computing",
        category: "Cloud Computing",
        instructor: "Michael Chen",
        skills: ["EC2", "S3", "Lambda", "CloudFormation", "DevOps"],
    },
    {
        id: "cyber-security",
        title: "Cyber Security & Ethical Hacking",
        description: "Comprehensive cybersecurity program covering ethical hacking and security protocols.",
        duration: "9",
        level: "Intermediate",
        price: "₹55,000",
        discountPrice: "₹35,000",
        monthlyPrice: "₹4,000/month",
        rating: 4.7,
        students: "2,800+",
        image: "/Ethical-Hacking-vs-Cyber-Security-1140x900-1.webp?height=250&width=400&text=Cyber+Security",
        category: "Cyber Security",
        instructor: "James Wilson",
        skills: ["Cryptography", "CISSP", "CEH", "Network Security", "Penetration Testing"], // , 
    },
    {
        id: "servicenow",
        title: "ServiceNow Certification Training",
        description: "Master ServiceNow with our comprehensive training, covering ITSM, ITOM, and CSM.",
        duration: "8",
        level: "Beginner to Advanced",
        price: "₹55,000",
        discountPrice: "₹35,000",
        monthlyPrice: "₹3,500/month",
        rating: 4.8,
        students: "1,500+",
        image: "/ServiceNow-Logo-1024x536.jpg?height=250&width=400&text=ServiceNow+Training",
        category: "ServiceNow",
        instructor: "David Smith",
        skills: ["ITSM", "ITOM", "CSM", "Workflow Automation", "Service Portal"],
    },
];


// from courses homepage
export const courses = [
    {
        id: "generative-ai",
        title: "Generative AI & Machine Learning",
        description: "Master the fundamentals of AI and ML with hands-on projects in GPT, DALL-E, and more.",
        duration: "12",
        level: "Beginner to Advanced",
        price: "₹55,000",
        discountPrice: "₹35,000",
        monthlyPrice: "₹2,333/month",
        rating: 4.8,
        students: "2,500+",
        image: "/placeholder.svg?height=200&width=300",
        skills: ["Python", "TensorFlow", "PyTorch", "OpenAI API", "Hugging Face"],
        category: "AI/ML",
    },
    {
        id: "deep-learning",
        title: "Deep Learning & Neural Networks",
        description: "Dive deep into neural networks, CNNs, RNNs, and advanced deep learning architectures.",
        duration: "10",
        level: "Intermediate",
        price: "₹55,000",
        discountPrice: "₹35,000",
        monthlyPrice: "₹2,560/month",
        rating: 4.7,
        students: "1,800+",
        image: "/placeholder.svg?height=200&width=300",
        skills: ["Keras", "TensorFlow", "Computer Vision", "NLP", "GANs"],
        category: "Deep Learning",
    },
    {
        id: "business-analytics",
        title: "AI for Business Analytics",
        description: "Apply AI and ML techniques to solve real-world business problems and drive insights.",
        duration: "8",
        level: "Beginner",
        price: "₹55,000",
        discountPrice: "₹35,000",
        monthlyPrice: "₹2,800/month",
        rating: 4.6,
        students: "3,200+",
        image: "/placeholder.svg?height=200&width=300",
        skills: ["Pandas", "Scikit-learn", "Tableau", "Power BI", "SQL"],
        category: "Business Analytics",
    },
    {
        id: "computer-vision",
        title: "Computer Vision & Image Processing",
        description: "Learn to build applications that can see and understand visual content.",
        duration: "9",
        level: "Intermediate",
        price: "₹55,000",
        discountPrice: "₹35,000",
        monthlyPrice: "₹2,667/month",
        rating: 4.7,
        students: "1,500+",
        image: "/placeholder.svg?height=200&width=300",
        skills: ["OpenCV", "YOLO", "CNN", "Image Segmentation", "Object Detection"],
        category: "Computer Vision",
    },
    {
        id: "nlp",
        title: "Natural Language Processing",
        description: "Build chatbots, sentiment analysis, and language models with advanced NLP techniques.",
        duration: "8",
        level: "Intermediate",
        price: "₹55,000",
        discountPrice: "₹35,000",
        monthlyPrice: "₹2,900/month",
        rating: 4.6,
        students: "1,200+",
        image: "/placeholder.svg?height=200&width=300",
        skills: ["NLTK", "spaCy", "BERT", "Transformers", "LangChain"],
        category: "NLP",
    },
    {
        id: "robotics",
        title: "AI Robotics & Automation",
        description: "Combine AI with robotics to create intelligent autonomous systems.",
        duration: "11",
        level: "Advanced",
        price: "₹55,000",
        discountPrice: "₹35,000",
        monthlyPrice: "₹2,764/month",
        rating: 4.8,
        students: "800+",
        image: "/placeholder.svg?height=200&width=300",
        skills: ["ROS", "Reinforcement Learning", "Control Systems", "Sensors", "Arduino"],
        category: "Robotics",
    },
];

// from ai category courses page
export const aicourses = [
    {
        id: "generative-ai-ml",
        title: "Generative AI & Machine Learning Master Program",
        description: "Comprehensive program covering GPT, DALL-E, ChatGPT, and advanced ML algorithms",
        duration: "12",
        level: "Beginner to Advanced",
        price: "₹55,000",
        discountPrice: "₹35,000",
        monthlyPrice: "₹2,333/month",
        rating: 4.8,
        students: "2,500+",
        image: "/placeholder.svg?height=200&width=300",
        skills: ["Python", "TensorFlow", "PyTorch", "OpenAI API", "Hugging Face"],
        instructor: "Dr. Rajesh Kumar",
        company: "Google AI",
    },
    {
        id: "deep-learning",
        title: "Deep Learning & Neural Networks",
        description: "Master CNNs, RNNs, GANs, and transformer architectures",
        duration: "10",
        level: "Intermediate",
        price: "₹55,000",
        discountPrice: "₹35,000",
        monthlyPrice: "₹3,500/month",
        rating: 4.7,
        students: "1,800+",
        image: "/placeholder.svg?height=200&width=300",
        skills: ["Keras", "TensorFlow", "Computer Vision", "NLP", "GANs"],
        instructor: "Dr. Priya Sharma",
        company: "Microsoft Research",
    },
    {
        id: "computer-vision",
        title: "Computer Vision & Image Processing",
        description: "Build applications that can see and understand visual content",
        duration: "9",
        level: "Intermediate",
        price: "₹55,000",
        discountPrice: "₹35,000",
        monthlyPrice: "₹3,167/month",
        rating: 4.7,
        students: "1,500+",
        image: "/placeholder.svg?height=200&width=300",
        skills: ["OpenCV", "YOLO", "CNN", "Image Segmentation", "Object Detection"],
        instructor: "Arjun Patel",
        company: "NVIDIA",
    },
    {
        id: "nlp",
        title: "Natural Language Processing",
        description: "Build chatbots, sentiment analysis, and language models",
        duration: "8",
        level: "Intermediate",
        price: "₹55,000",
        discountPrice: "₹35,000",
        monthlyPrice: "₹4,000/month",
        rating: 4.6,
        students: "1,200+",
        image: "/placeholder.svg?height=200&width=300",
        skills: ["NLTK", "spaCy", "BERT", "Transformers", "LangChain"],
        instructor: "Sneha Reddy",
        company: "OpenAI",
    },
    {
        id: "reinforcement-learning",
        title: "Reinforcement Learning",
        description: "Learn how to build intelligent agents that learn from interaction",
        duration: "7",
        level: "Advanced",
        price: "₹55,000",
        discountPrice: "₹35,000",
        monthlyPrice: "₹4,100/month",
        rating: 4.5,
        students: "800+",
        image: "/placeholder.svg?height=200&width=300",
        skills: ["Q-Learning", "Policy Gradients", "Actor-Critic", "OpenAI Gym", "Stable Baselines"],
        instructor: "Dr. Vikram Singh",
        company: "DeepMind",
    },
    {
        id: "ai-robotics",
        title: "AI Robotics & Automation",
        description: "Combine AI with robotics to create intelligent autonomous systems",
        duration: "11",
        level: "Advanced",
        price: "₹55,000",
        discountPrice: "₹35,000",
        monthlyPrice: "₹2,764/month",
        rating: 4.8,
        students: "600+",
        image: "/placeholder.svg?height=200&width=300",
        skills: ["ROS", "Reinforcement Learning", "Control Systems", "Sensors", "Arduino"],
        instructor: "Dr. Anita Gupta",
        company: "Tesla",
    },
];

export const cybersecuritycourses = [
    {
        id: "ethical-hacking",
        title: "Certified Ethical Hacker (CEH) Master Program",
        description: "Learn ethical hacking techniques and penetration testing methodologies",
        duration: "8",
        level: "Intermediate",
        price: "₹55,000",
        discountPrice: "₹35,000",
        monthlyPrice: "₹3,200/month",
        rating: 4.8,
        students: "2,800+",
        image: "/placeholder.svg?height=200&width=300",
        skills: ["Penetration Testing", "Kali Linux", "Network Security", "Web Security", "Cryptography"],
        instructor: "Rajesh Kumar",
        company: "EC-Council",
    },
    {
        id: "cybersecurity-analyst",
        title: "Cybersecurity Analyst Certification",
        description: "Master threat detection, incident response, and security operations",
        duration: "10",
        level: "Beginner to Advanced",
        price: "₹55,000",
        discountPrice: "₹35,000",
        monthlyPrice: "₹2,800/month",
        rating: 4.7,
        students: "3,200+",
        image: "/placeholder.svg?height=200&width=300",
        skills: ["SIEM", "Incident Response", "Threat Hunting", "Forensics", "Risk Assessment"],
        instructor: "Dr. Priya Sharma",
        company: "IBM Security",
    },
    {
        id: "network-security",
        title: "Network Security & Firewall Management",
        description: "Secure network infrastructure and implement firewall solutions",
        duration: "7",
        level: "Intermediate",
        price: "₹55,000",
        discountPrice: "₹35,000",
        monthlyPrice: "₹3,200/month",
        rating: 4.6,
        students: "2,100+",
        image: "/placeholder.svg?height=200&width=300",
        skills: ["Firewalls", "VPN", "IDS/IPS", "Network Monitoring", "Access Control"],
        instructor: "Arjun Patel",
        company: "Cisco",
    },
    {
        id: "cloud-security",
        title: "Cloud Security Specialist",
        description: "Secure cloud environments and implement cloud security best practices",
        duration: "9",
        level: "Advanced",
        price: "₹55,000",
        discountPrice: "₹35,000",
        monthlyPrice: "₹3,378/month",
        rating: 4.5,
        students: "1,500+",
        image: "/placeholder.svg?height=200&width=300",
        skills: ["AWS Security", "Azure Security", "Cloud Compliance", "Container Security", "DevSecOps"],
        instructor: "Vikram Singh",
        company: "Palo Alto Networks",
    },
    {
        id: "digital-forensics",
        title: "Digital Forensics & Investigation",
        description: "Learn digital evidence collection and forensic analysis techniques",
        duration: "8",
        level: "Advanced",
        price: "₹55,000",
        discountPrice: "₹35,000",
        monthlyPrice: "₹3,000/month",
        rating: 4.4,
        students: "1,200+",
        image: "/placeholder.svg?height=200&width=300",
        skills: ["Digital Forensics", "Evidence Collection", "Malware Analysis", "Mobile Forensics", "Legal Procedures"],
        instructor: "Dr. Anita Gupta",
        company: "SANS Institute",
    },
    {
        id: "application-security",
        title: "Application Security & Secure Coding",
        description: "Build secure applications and implement security in SDLC",
        duration: "6",
        level: "Intermediate",
        price: "₹55,000",
        discountPrice: "₹35,000",
        monthlyPrice: "₹3,467/month",
        rating: 4.3,
        students: "1,800+",
        image: "/placeholder.svg?height=200&width=300",
        skills: ["Secure Coding", "OWASP", "Code Review", "Security Testing", "DevSecOps"],
        instructor: "Sneha Reddy",
        company: "Checkmarx",
    },
]


export const DataSciencecourses = [
    {
        id: "data-science-python-master",
        title: "Data Science with Python Master Program",
        description:
            "Complete data science program covering statistics, machine learning, and data visualization with Python",
        duration: "12",
        level: "Beginner to Advanced",
        price: "₹55,000",
        discountPrice: "₹35,000",
        monthlyPrice: "₹2,917/month",
        rating: 4.9,
        students: "8,200+",
        image: "/placeholder.svg?height=200&width=300",
        skills: ["Python", "Pandas", "NumPy", "Matplotlib", "Scikit-learn", "SQL", "Tableau"],
        instructor: "Dr. Amit Sharma",
        company: "Netflix",
        type: "Master Program",
        projects: 15,
    },
    {
        id: "data-analytics-business",
        title: "Business Data Analytics & Intelligence",
        description: "Learn to analyze business data and create actionable insights for decision making",
        duration: "8",
        level: "Beginner",
        price: "₹55,000",
        discountPrice: "₹35,000",
        monthlyPrice: "₹3,500/month",
        rating: 4.8,
        students: "6,500+",
        image: "/placeholder.svg?height=200&width=300",
        skills: ["Tableau", "Power BI", "SQL", "Excel", "Statistics", "R", "Business Intelligence"],
        instructor: "Priya Mehta",
        company: "Microsoft",
        type: "Analytics Program",
        projects: 12,
    },
    {
        id: "big-data-analytics",
        title: "Big Data Analytics with Hadoop & Spark",
        description: "Master big data technologies and distributed computing for large-scale data processing",
        duration: "10",
        level: "Intermediate",
        price: "₹55,000",
        discountPrice: "₹35,000",
        monthlyPrice: "₹3,200/month",
        rating: 4.7,
        students: "4,200+",
        image: "/placeholder.svg?height=200&width=300",
        skills: ["Hadoop", "Spark", "Hive", "HBase", "Kafka", "Scala", "NoSQL"],
        instructor: "Rajesh Kumar",
        company: "Cloudera",
        type: "Big Data Program",
        projects: 10,
    },
    {
        id: "data-visualization",
        title: "Data Visualization & Storytelling",
        description: "Create compelling visualizations and tell stories with data using modern tools",
        duration: "6",
        level: "Beginner",
        price: "₹55,000",
        discountPrice: "₹35,000",
        monthlyPrice: "₹4,000/month",
        rating: 4.6,
        students: "5,800+",
        image: "/placeholder.svg?height=200&width=300",
        skills: ["D3.js", "Tableau", "Power BI", "Python", "R", "Plotly", "Seaborn"],
        instructor: "Sneha Patel",
        company: "Uber",
        type: "Visualization Course",
        projects: 8,
    },
    {
        id: "statistical-analysis-r",
        title: "Statistical Analysis with R",
        description: "Master statistical concepts and R programming for advanced data analysis",
        duration: "7",
        level: "Intermediate",
        price: "₹55,000",
        discountPrice: "₹35,000",
        monthlyPrice: "₹3,657/month",
        rating: 4.5,
        students: "3,500+",
        image: "/placeholder.svg?height=200&width=300",
        skills: ["R Programming", "Statistics", "Data Mining", "Regression", "Hypothesis Testing", "ANOVA"],
        instructor: "Dr. Vikram Singh",
        company: "Stanford University",
        type: "Statistics Course",
        projects: 9,
    },
    {
        id: "data-engineering-pipeline",
        title: "Data Engineering & Pipeline Development",
        description: "Build robust data pipelines and infrastructure for scalable data systems",
        duration: "9",
        level: "Advanced",
        price: "₹55,000",
        discountPrice: "₹35,000",
        monthlyPrice: "₹3,733/month",
        rating: 4.4,
        students: "2,800+",
        image: "/placeholder.svg?height=200&width=300",
        skills: ["Apache Airflow", "Docker", "Kubernetes", "AWS", "Python", "ETL", "Data Warehousing"],
        instructor: "Arjun Gupta",
        company: "Airbnb",
        type: "Engineering Course",
        projects: 11,
    },
]
